# Generated by Django 4.2.21 on 2026-06-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingwebhookpayload',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomingwebhookpayload',
            name='max_retry_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='incomingwebhookpayload',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomingwebhookpayload',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
