# Generated by Django 4.2.21 on 2026-06-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaplatformline',
            name='platform',
            field=models.CharField(choices=[('meta', 'Meta'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('google_ads', 'Google Ads'), ('website', 'Website')], max_length=40),
        ),
    ]
