# Generated by Django 4.2.21 on 2026-06-23 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('leads', '0002_initial'),
        ('marketing', '0002_alter_socialmediaplatformline_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attended', models.BooleanField(default=False)),
                ('platform', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='actual_attendees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='campaign_end_date_gte_start_date'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(('total_budget__gte', 0)), name='campaign_total_budget_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='campaignevent',
            constraint=models.CheckConstraint(check=models.Q(('budget__gte', 0)), name='campaign_event_budget_non_negative'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='companies.company'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='marketing.campaignevent'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
