# Generated by Django 4.2.21 on 2026-06-23 18:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_eventattendance_campaignevent_actual_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('semi_approved', 'Semi Approved'), ('not_approved', 'Not Approved')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='campaignevent',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='campaignothercost',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='eventcatering',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='eventcelebrity',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='eventgiveaway',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='exhibitionrecord',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='socialmediaplatformline',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='streetad',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='streetadlocation',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='streetadtypeline',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='tvad',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='tvadchannel',
            name='channel_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='campaignothercost',
            constraint=models.CheckConstraint(check=models.Q(('value__gte', 0)), name='campaign_other_cost_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='eventcatering',
            constraint=models.CheckConstraint(check=models.Q(('budget__gte', 0)), name='event_catering_budget_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='eventcelebrity',
            constraint=models.CheckConstraint(check=models.Q(('budget__gte', 0)), name='event_celebrity_budget_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='eventgiveaway',
            constraint=models.CheckConstraint(check=models.Q(('budget__gte', 0)), name='event_giveaway_budget_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='exhibitionrecord',
            constraint=models.CheckConstraint(check=models.Q(('budget__gte', 0)), name='exhibition_record_budget_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='socialmediaplatformline',
            constraint=models.CheckConstraint(check=models.Q(('budget__gte', 0)), name='social_media_platform_line_budget_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='streetad',
            constraint=models.CheckConstraint(check=models.Q(('budget__gte', 0)), name='street_ad_budget_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='streetadlocation',
            constraint=models.CheckConstraint(check=models.Q(('budget__gte', 0)), name='street_ad_location_budget_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='streetadtypeline',
            constraint=models.CheckConstraint(check=models.Q(('budget__gte', 0)), name='street_ad_type_line_budget_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tvad',
            constraint=models.CheckConstraint(check=models.Q(('budget__gte', 0)), name='tv_ad_budget_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tvadchannel',
            constraint=models.CheckConstraint(check=models.Q(('channel_budget__gte', 0)), name='tv_ad_channel_budget_non_negative'),
        ),
    ]
