# Generated by Django 4.2.21 on 2026-06-23 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('accounts', '0002_initial'),
        ('sla', '0001_initial'),
        ('distribution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentattempt',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_attempts', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='sla_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_attempts', to='sla.leadslainstance'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_attempts', to='accounts.team'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rotationpointer',
            index=models.Index(fields=['company', 'strategy_code', 'scope_mode'], name='distributio_company_c7a292_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rotationpointer',
            unique_together={('company', 'strategy_code', 'scope_mode', 'team')},
        ),
    ]
